#!/usr/bin/env python3
"""
Generate one short high-quality MP3 clip per unique Spanish phrase used on the
site (glossary terms, flashcards, Playscape dialogue), using Microsoft Edge's
free neural TTS (edge-tts). Output goes to audio/es/<hash>.mp3, plus a JS
lookup map (es_audio_map.js) from phrase -> file path that the site's
speakText()/speakMessage() functions check before falling back to
ResponsiveVoice.

Re-run anytime new Spanish content is added — already-generated clips are
skipped (idempotent, keyed by content hash).
"""
import asyncio
import hashlib
import importlib.util
import json
import re
import sys

import edge_tts

VOICE_ES = "es-US-PalomaNeural"  # Latin American Spanish, female neural voice
RATE = "-10%"  # slightly slower, matches the site's existing TTS pacing
OUT_DIR = "audio/es"
MAP_FILE = "es_audio_map.js"


def slug(text):
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:12]


def collect_glossary_terms():
    with open("index.html", encoding="utf-8") as f:
        content = f.read()
    m = re.search(r"const GLOSSARY_DATA = (\{.*?\n\});", content, re.DOTALL)
    data = json.loads(m.group(1))
    terms = set()
    for items in data.values():
        for item in items:
            sp = item.get("spanish", "").strip()
            if sp:
                terms.add(sp)
    return terms


def collect_playscape_lines():
    spec = importlib.util.spec_from_file_location("gp", "generate_playscape.py")
    gp = importlib.util.module_from_spec(spec)
    # generate_playscape.py writes playscape.html as a side effect of import;
    # that's fine, it's idempotent and produces the same file we already have.
    spec.loader.exec_module(gp)
    lines = set()
    for chat in gp.chats:
        for msg in chat["messages"]:
            if msg["lang"] == "es" and msg["text"].strip():
                lines.add(msg["text"].strip())
    return lines


async def generate_one(text, sem, retries=3):
    import os

    path = f"{OUT_DIR}/{slug(text)}.mp3"
    if os.path.exists(path):
        return text, path, True
    async with sem:
        for attempt in range(retries):
            try:
                comm = edge_tts.Communicate(text, VOICE_ES, rate=RATE)
                await comm.save(path)
                return text, path, True
            except Exception as e:
                if attempt < retries - 1:
                    await asyncio.sleep(2 * (attempt + 1))
                else:
                    print(f"FAILED: {text!r}: {e}", file=sys.stderr)
                    return text, path, False


async def main():
    import os

    os.makedirs(OUT_DIR, exist_ok=True)

    terms = collect_glossary_terms() | collect_playscape_lines()
    print(f"{len(terms)} unique Spanish phrases to synthesize")

    sem = asyncio.Semaphore(5)
    results = await asyncio.gather(*[generate_one(t, sem) for t in sorted(terms)])

    audio_map = {}
    failures = 0
    for text, path, ok in results:
        if ok:
            audio_map[text] = path
        else:
            failures += 1

    with open(MAP_FILE, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by generate_es_tts_clips.py — do not hand-edit.\n")
        f.write("const ES_AUDIO_MAP = ")
        f.write(json.dumps(audio_map, ensure_ascii=False, indent=2))
        f.write(";\n")

    print(f"Done. {len(audio_map)} clips ready, {failures} failed.")
    print(f"Map written to {MAP_FILE}")


if __name__ == "__main__":
    asyncio.run(main())
